# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

# in _config.yml

title: Energy Efficiency Shipping
author: wengang.mao@chalmers.se
logo: contents/images/voysmart.png


# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force